#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"syscall/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li.d \$a7, SYS_${name}\n";
    print " syscall 0\n";
    print " jirl \$zero, \$ra, 0\n";
}

entry("fork");
entry("exit");
entry("wait");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("execve");
entry("openat");
entry("unlinkat");
entry("fstat");
entry("linkat");
entry("mkdirat");
entry("mknod");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("brk");
entry("sleep");
entry("uptime");

# fs

entry("exec");
entry("pipe2");
entry("getcwd");
entry("dup3");
entry("getdents64");
entry("mount");
entry("umount2");
entry("mmap");
entry("munmap");
entry("times");


# proc
entry("waitpid");
entry("wait4");
entry("shutdown");
entry("clone");
entry("getppid");
entry("set_tid_address");
entry("getuid");
entry("setuid");
entry("getgid");
entry("setgid");
entry("geteuid");
entry("getegid");
entry("setreuid");
entry("setregid");
entry("fcntl");
entry("exit_group");
entry("futex");

entry("kills");
entry("tkill");
entry("tgkill");
entry("rt_sigaction");
entry("rt_sigprocmask");
entry("rt_sigtimedwait");
entry("rt_sigreturn");
entry("sendfile");
entry("ppoll");
entry("gettid");
entry("writev");
entry("set_robust_list");
entry("readlinkat");
entry("clock_gettime");
entry("prlimit64");
entry("getrandom");
entry("fstatat");
entry("ioctl");
entry("syslog");
entry("faccessat");
entry("sysinfo");
entry("clock_nanosleep");
entry("copy_file_range");
entry("ftruncate");
entry("splice");
entry("fchmodat");
entry("symlinkat");
entry("fsync");
entry("fdatasync");
entry("fchownat");
entry("fchown");